name: (4.x) Offline installation test
on:
  pull_request:
    paths:
      - 'install_functions/wazuh-offline-download.sh'
      - 'install_functions/wazuh-offline-installation.sh'
      - '.github/workflows/4_offline_installation.yml'
  workflow_dispatch:
    inputs:
      WAZUH_INSTALLATION_ASSISTANT_REFERENCE:
        description: "Branch or tag of the wazuh-installation-assistant repository."
        required: true
        default: 4.10.5
env:
  S3_PATH: s3://${{ secrets.CI_DEV_INTERNAL_S3_BUCKET }}/wazuh-installation-assistant/4_offline_installation
jobs:
  Build-wazuh-install-script:
    runs-on: codebuild-github-actions-codebuild-runner-devops-amd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.WAZUH_INSTALLATION_ASSISTANT_REFERENCE }}

      - name: Build wazuh-install script and use staging packages
        run: bash builder.sh -i

      - name: Upload wazuh-install.sh artifact to S3
        run: aws s3 cp ./wazuh-install.sh "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/"

  Test-offline-installation-debian:
    runs-on: codebuild-github-actions-codebuild-runner-devops-amd-${{ github.run_id }}-${{ github.run_attempt }}
    needs: Build-wazuh-install-script
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.WAZUH_INSTALLATION_ASSISTANT_REFERENCE }}

      - name: Download wazuh-install.sh artifact to S3
        run: aws s3 cp "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/wazuh-install.sh" .

      - name: Move installation assistant script
        run: cp $GITHUB_WORKSPACE/wazuh-install.sh $GITHUB_WORKSPACE/.github/actions/offline-installation/wazuh-install.sh

      - name: Run script
        run: sudo bash $GITHUB_WORKSPACE/.github/actions/offline-installation/offline-installation.sh

  Test-offline-installation-rpm:
    runs-on: codebuild-github-actions-codebuild-runner-devops-amd-${{ github.run_id }}-${{ github.run_attempt }}
    needs: Build-wazuh-install-script
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.WAZUH_INSTALLATION_ASSISTANT_REFERENCE }}

      - name: Download wazuh-install.sh artifact to S3
        run: aws s3 cp "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/wazuh-install.sh" .

      - name: Move installation assistant script
        run: cp $GITHUB_WORKSPACE/wazuh-install.sh $GITHUB_WORKSPACE/.github/actions/offline-installation/wazuh-install.sh

      - name: Launch docker and run script
        run: sudo docker run -v $GITHUB_WORKSPACE/.github/actions/offline-installation/:/tests centos:centos7 bash /tests/offline-installation.sh
