name: (4.x) Password tool and wazuh-install scripts
on:
  pull_request:
    paths:
      - 'passwords_tool/**'
      - '.github/workflows/4_password_tool.yml'

env:
  S3_PATH: s3://${{ secrets.CI_DEV_INTERNAL_S3_BUCKET }}/wazuh-installation-assistant/4_password_tool

jobs:
  Build-password-tool-and-wazuh-install-scripts:
    runs-on: codebuild-github-actions-codebuild-runner-devops-amd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - name: Build password-tool and wazuh-install scripts
        run: |
          bash builder.sh -p
          bash builder.sh -i
        shell: bash
      - run: |
          aws s3 cp ./wazuh-install.sh "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/"
          aws s3 cp ./wazuh-passwords-tool.sh "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/"

  test-password-tool-success:
    runs-on: codebuild-github-actions-codebuild-runner-devops-amd-${{ github.run_id }}-${{ github.run_attempt }}
    needs: Build-password-tool-and-wazuh-install-scripts
    steps:
      - uses: actions/checkout@v4
      - run: |
          aws s3 cp "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/wazuh-install.sh" .
          aws s3 cp "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/wazuh-passwords-tool.sh" .
      - name: Install wazuh
        run: |
          sudo bash wazuh-install.sh -a -v
      - name: Uncompress wazuh install files
        run: sudo tar -xvf wazuh-install-files.tar
      - name: Run script
        run: sudo bash .github/actions/passwords-tool/tests-stack-success.sh

  test-password-tool-failure:
    runs-on: codebuild-github-actions-codebuild-runner-devops-amd-${{ github.run_id }}-${{ github.run_attempt }}
    needs: Build-password-tool-and-wazuh-install-scripts
    steps:
      - uses: actions/checkout@v4
      - run: |
          aws s3 cp "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/wazuh-install.sh" .
          aws s3 cp "${{ env.S3_PATH }}/${{ github.run_id }}/scripts/wazuh-passwords-tool.sh" .
      - name: Install wazuh
        run: |
          sudo bash wazuh-install.sh -a -v
      - name: Uncompress wazuh install files
        run: sudo tar -xvf wazuh-install-files.tar
      - name: Run script
        run: sudo bash .github/actions/passwords-tool/tests-stack-failure.sh
